In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv(r"C:\Users\stran\Desktop\DS\Student Performance analyzer\student_performance_dataset.csv")
df.head()

,Student_ID,Math,Physics,Chemistry,English,Computer_Science,Attendance_Percent,Study_Hours_Per_Day,Average_Marks,Final_Grade
0,S001,82.0,70.0,42,52,81,69.0,4.5,65.4,C
1,S002,60.0,67.0,56,37,75,82.0,1.7,59.0,C
2,S003,58.0,68.0,54,49,72,57.0,-1.0,60.2,C
3,S004,92.0,80.0,80,81,90,72.0,1.7,84.6,B
4,S005,NaN,NaN,85,66,65,NaN,NaN,72.0,B

In [3]:
df.describe()

,Math,Physics,Chemistry,English,Computer_Science,Attendance_Percent,Study_Hours_Per_Day,Average_Marks
count,110.000000,110.000000,120.000000,120.000000,120.000000,110.000000,111.000000,120.000000
mean,68.036364,67.781818,66.250000,67.991667,70.525000,77.236364,2.521622,68.335556
std,19.374118,18.192842,18.122019,19.648378,17.769752,16.342059,1.544928,9.670937
min,35.000000,35.000000,35.000000,35.000000,40.000000,55.000000,-1.000000,38.600000
25%,51.000000,51.000000,52.000000,52.000000,55.750000,64.000000,1.200000,60.750000
50%,68.500000,68.500000,68.500000,68.500000,72.000000,75.000000,2.700000,67.400000
75%,84.750000,83.000000,80.000000,85.250000,86.000000,87.000000,3.800000,75.750000
max,99.000000,99.000000,99.000000,99.000000,99.000000,120.000000,4.900000,95.333333

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student_ID           120 non-null    object
 1   Math                 110 non-null    float64
 2   Physics              110 non-null    float64
 3   Chemistry            120 non-null    int64
 4   English              120 non-null    int64
 5   Computer_Science     120 non-null    int64
 6   Attendance_Percent   110 non-null    float64
 7   Study_Hours_Per_Day  111 non-null    float64
 8   Average_Marks        120 non-null    float64
 9   Final_Grade          120 non-null    object
dtypes: float64(5), int64(3), object(2)
memory usage: 9.5+ KB

In [5]:
df.isnull().sum()

Student_ID              0
Math                   10
Physics                10
Chemistry               0
English                 0
Computer_Science        0
Attendance_Percent     10
Study_Hours_Per_Day     9
Average_Marks           0
Final_Grade             0
dtype: int64

In [6]:
df["Math"].fillna(df["Math"].mean(),inplace=True)

C:\Users\stran\AppData\Local\Temp\ipykernel_21252\133823511.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Math"].fillna(df["Math"].mean(),inplace=True)

In [7]:
df["Math"].isnull().sum()

np.int64(0)

In [15]:
df["Math"]

0      82.000000
1      60.000000
2      58.000000
3      92.000000
4      68.036364
         ...
115    94.000000
116    98.000000
117    63.000000
118    51.000000
119    40.000000
Name: Math, Length: 120, dtype: float64

In [9]:
df["Physics"].fillna(df["Physics"].mean(),inplace=True)

C:\Users\stran\AppData\Local\Temp\ipykernel_21252\991346202.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Physics"].fillna(df["Physics"].mean(),inplace=True)

In [16]:
df["Physics"].isnull().sum()

np.int64(0)

In [17]:
df["Physics"]

0      70.000000
1      67.000000
2      68.000000
3      80.000000
4      67.781818
         ...
115    82.000000
116    46.000000
117    71.000000
118    78.000000
119    88.000000
Name: Physics, Length: 120, dtype: float64

In [18]:
df["Attendance_Percent"].fillna(df["Attendance_Percent"].mean(),inplace=True)

C:\Users\stran\AppData\Local\Temp\ipykernel_21252\4172185777.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Attendance_Percent"].fillna(df["Attendance_Percent"].mean(),inplace=True)

In [19]:
df["Attendance_Percent"].isnull().sum()

np.int64(0)